apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: distcc
  name: distcc
spec:
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      labels:
        app: distcc
    spec:
      containers:
        - image: >-
            ai-search-registry-vpc.cn-shanghai.cr.aliyuncs.com/devops/distcc:latest
          imagePullPolicy: Always
          name: distcc
          ports:
            - containerPort: 3632
              name: port
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      imagePullSecrets:
        - name: ai-search-hub

---
apiVersion: v1
kind: Service
metadata:
  name: distcc-svc
spec:
  ports:
    - name: distcc
      nodePort: 30000
      port: 3632
      protocol: TCP
      targetPort: 3632
  selector:
    app: distcc
  type: NodePort
